## Configuracion de Spring
spring:
  application:
    name: ms-boats
  datasource:
    url: jdbc:postgresql://localhost:5432/represa_prado_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create

## Configuracion de Instancia 
server:
  port: 8089

## Configuracion del cliente de Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: ms-hotels
